config/routes.rb
So::Application.routes.draw do

  concern :comment_and_vote do
    resources :comments
    resources :votes
  end
  

  resources :questions, concerns: :comment_and_vote do
    resources :answers
  end

  resources :answers, only: [], concerns: :comment_and_vote

  resources :comments, only: [] do
    resources :votes
  end

  devise_for :users
  resources :user, only: :show

  root to: "questions#index"
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  include VoteTracker

  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable

  validates_presence_of :content, :question_id, :user_id

  extend FriendlyId
  friendly_id :random_id, use: [:slugged, :finders]

  private

  def random_id
    SecureRandom.hex(16) # Silly at this point, but whatever
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include VoteTracker

  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates_presence_of :user_id, :commentable_id, :content

end

app/models/concerns/vote_tracker.rb
module VoteTracker

  extend ActiveSupport::Concern

  included do
    has_many :votes, as: :voteable
    default_scope order: "vote_count desc" # Don't use a default_scope.  Bad things happen
  end

end

app/models/question.rb
class Question < ActiveRecord::Base

  include VoteTracker

  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable

  validates_presence_of :content, :user_id

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  default_scope order: "created_at desc" # Don't use a default_scope.  Bad things happen

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes

  extend FriendlyId
  friendly_id :username, use: [:slugged, :finders]
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  DIRECTIONS = [1, -1]
  VOTEABLE = [Answer, Comment, Question]

  belongs_to :voteable, polymorphic: true
  belongs_to :user

  validates :direction, presence: true, inclusion: { in: DIRECTIONS } # -1 = down; 1 = up;
  validates_presence_of :user_id, :voteable_id
  validates_uniqueness_of :user_id, scope: :voteable_id

  after_save :cache_vote_count_on_parent

  def self.direction_to_string(dir)
    case dir
    when 1
      "&#8593;"
    else
      "&#8595;"
    end
  end

  # This should really be thrown in to a queue for background processing.
  # No need to keep it in the main thread
  def cache_vote_count_on_parent
    voteable.update_attributes(vote_count: voteable.votes.sum(:direction))
  end

end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base

  belongs_to :question
  before_filter :authenticate_user!

  respond_to :html, :js

  def create
    @answer = Answer.new(permitted_params[:answer])
    @answer.user = current_user
    @answer.question = parent
    create! { question_url(parent) }
  end

  private

  def permitted_params
    params.permit(answer: [
      :title, :content
    ])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base

  belongs_to :question, :answer, polymorphic: true
  actions :create, :update, :destroy

  before_filter :authenticate_user!
  respond_to :html, :js

  def create
    @comment = Comment.new(permitted_params[:comment])
    @comment.user = current_user
    @comment.commentable = parent
    create!
  end

  private

  def permitted_params
    params.permit(comment: [
      :content
    ])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base

  before_filter :authenticate_user!, except: [:index, :show]

  def create
    @question = Question.new(permitted_params[:question])
    @question.user = current_user
    create!
  end

  private

  def permitted_params
    params.permit(question: [
      :title, :content
    ])
  end

end

app/controllers/votes_controller.rb
class VotesController < InheritedResources::Base

  belongs_to :comment, :answer, :question, polymorphic: true
  actions :create, :update, :destroy

  before_filter :authenticate_user!
  before_filter :delete_existing_vote
  respond_to :html, :js

  def create
    @vote = Vote.new(permitted_params[:vote])
    @vote.user = current_user
    @vote.voteable = parent
    create!
  end

  private

  # This is probably not the best way to do it.  But it works for a prototype
  def delete_existing_vote
    parent.votes.where{user_id.eq my{current_user.id}}.destroy_all
  end

  def permitted_params
    params.permit(vote: [
      :direction
    ])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title, meta_title = page_title, options = {})
    meta_title = meta_title.blank? ? page_title : meta_title
    content_for(:title, truncate(meta_title.gsub(/[^0-9A-Za-z--\/'\. ]/, ''), length: 75) + " | Stack Overflow")
    content_tag(:h1, page_title, options.merge!(class: "page-header"))
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.haml
- if user_signed_in?
  %h5 Got An Answer?
  = simple_form_for [question, Answer.new], remote: true, html: { id: "new-answer-form" } do |f|
    = f.input :content, label: "Answer", input_html: { class: "new-answer-content" }
    = f.submit "Submit Answer", class: "btn btn-primary"
- else
  = link_to "Sign in to Post an Answer", new_user_session_path, class: "btn btn-info"
%hr

app/views/answers/_rendered_answer.html.haml
.row
  .col-lg-12
    .well
      .row
        .col-sm-1
          = render "votes/voting", voteable: answer
        .col-sm-11
          %p= answer.content
          %p
            = render "components/poster", postable: answer
          = render "comments/comment_area", commentable: answer

app/views/answers/create.js.erb
$("#question-answers").prepend("<%= j render "rendered_answer", answer: resource %>");
$(".new-answer-content").val("");

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %tr
    %th Slug
    %th Content
    %th Question
    %th User
    %th
    %th
    %th

  - @answers.each do |answer|
    %tr
      %td= answer.slug
      %td= answer.content
      %td= answer.question
      %td= answer.user
      %td= link_to 'Show', answer
      %td= link_to 'Edit', edit_answer_path(answer)
      %td= link_to 'Destroy', answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Slug:
  = @answer.slug
%p
  %b Content:
  = @answer.content
%p
  %b Question:
  = @answer.question
%p
  %b User:
  = @answer.user

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path

app/views/comments/_comment_area.html.haml
.comment-area
  .comments{id: "comments-#{commentable.class.name.downcase}-#{commentable.id}"}
    - commentable.comments.each do |comment|
      = render "comments/rendered_comment", comment: comment
  = render "comments/form", commentable: commentable, comment: Comment.new

app/views/comments/_form.html.haml
- if user_signed_in?
  = simple_form_for([commentable, comment], remote: true) do |f|
    = f.input :content, label: "Share a Comment", input_html: { class: "comment-field-#{commentable.class.name.downcase}-#{commentable.id}" }
    = f.submit "Post Comment", class: "btn btn-info"
- else
  %small= link_to "Sign In to Comment", new_user_session_path(back_to: url_for(resource))

app/views/comments/_rendered_comment.html.haml
.row
  .col-sm-1
    = render "votes/voting", voteable: comment
  .col-sm-11
    %p.comment
      = comment.content
      %br
      = render "components/poster", postable: comment
%hr

app/views/comments/create.js.erb
$("#comments-<%= resource.commentable.class.name.downcase %>-<%= resource.commentable.id %>")
  .append("<%= j render "rendered_comment", comment: resource %>");
  
$(".comment-field-<%= resource.commentable.class.name.downcase %>-<%= resource.commentable.id %>")
  .val("");

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield(:title)
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render "components/navbar"
    .container
      = yield

app/views/questions/_form.html.haml
= simple_form_for resource do |f|
  = f.input :title
  = f.input :content

  = f.submit "Submit Question", class: "btn btn-primary"

app/views/questions/_info.html.haml
.col-sm-1
  = render "votes/voting", voteable: question
.col-sm-11
  %h3= link_to question.title, question
  %p
    = render "components/poster", postable: question

  - if local_assigns.has_key?(:show_comments) && show_comments
    = render "comments/comment_area", commentable: resource

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
= title("Latest Questions")
- collection.each do |question|
  .row
    .col-lg-12
      .well
        = render "info", question: question

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.haml
= title(resource.title)
.row
  = render "info", question: resource, show_comments: true

.row
  .col-sm-11.col-sm-offset-1
    %hr

    = render "answers/form", question: resource

    #question-answers
      - resource.answers.each do |answer|
        = render "answers/rendered_answer", answer: answer

app/views/votes/_form.html.haml
= simple_form_for([voteable, Vote.new], remote: true) do |f|
  = f.input :direction, as: :hidden, input_html: { value: direction }
  = f.submit Vote.direction_to_string(direction).html_safe, class: "btn btn-warning"

app/views/votes/_voting.html.haml
.text-center{class: "voteable-#{voteable.class.name.downcase}-#{voteable.id}"}
  = render "votes/form", voteable: voteable, direction: Vote::DIRECTIONS.first
  %p.lead.vote-count= voteable.vote_count
  = render "votes/form", voteable: voteable, direction: Vote::DIRECTIONS.last    

app/views/votes/create.js.erb
$(".voteable-<%= resource.voteable.class.name.downcase %>-<%= resource.voteable.id %> .vote-count").html("<%= resource.voteable.vote_count %>");